#! /usr/bin/env python
# -*- coding: utf-8 -*-
from selenium import webdriver
import os
import time

#chromepath = os.path.abspath(r"/usr/local/share/chromedriver")
#driver = webdriver.Chrome(chromepath)
driver = webdriver.Chrome()
driver.get("https://shop.dianjia.io")
driver.find_element_by_id("brandId").send_keys("10010")
driver.find_element_by_id("username").send_keys("15868974532")
driver.find_element_by_id("password").send_keys("123456")
driver.find_element_by_id("popup-submit").click()
print driver.title